import urllib,urllib2,re,cookielib,string
import xbmc, xbmcgui, xbmcaddon, xbmcplugin
from resources.libs import main

#Mash Up - by Mash2k3 2012.

addon_id = 'plugin.video.movie25'
selfAddon = xbmcaddon.Addon(id=addon_id)



def SKYSPORTS():
        main.addDir('All Videos','http://www1.skysports.com/watch/more/5/27452/200/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Sports','http://www1.skysports.com/watch/tv-shows',178,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('TV Shows','http://www1.skysports.com/watch/tv-shows',175,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))


def SKYSPORTSCAT():
        main.addDir('Sports [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/28461/200/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Football','football',179,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Formula 1','formula-1',179,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Cricket','http://www1.skysports.com//watch/video/sports/cricket',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Rugby Union','rugby-union',179,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Rugby League','http://www1.skysports.com//watch/video/sports/rugby-league',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Golf','http://www1.skysports.com//watch/video/sports/golf',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Tennis','http://www1.skysports.com//watch/video/sports/tennis',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Boxing','http://www1.skysports.com//watch/video/sports/boxing',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('NFL','http://www1.skysports.com//watch/video/sports/nfl',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Racing','http://www1.skysports.com//watch/video/sports/racing',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Darts','http://www1.skysports.com//watch/video/sports/darts',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Basketball','http://www1.skysports.com//watch/video/sports/basketball',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Cycling','http://www1.skysports.com//watch/video/sports/cycling',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Speedway','http://www1.skysports.com//watch/video/sports/speedway',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('Ice Hockey','http://www1.skysports.com//watch/video/sports/ice-hockey',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('UFC','http://www1.skysports.com//watch/video/sports/ufc',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        main.addDir('WWE','http://www1.skysports.com//watch/video/sports/wwe',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))

def SKYSPORTSCAT2(murl):
        if murl=='football':
                main.addDir('Football [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/12606/200/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Premier League','premier-league',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Championship','championship',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('League One','league-one',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('League Two','league-two',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Scottish Football','scottish-football',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Primera Liga','primera-liga',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Champions League','http://www1.skysports.com/watch/video/sports/football/competitions/champions-league',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Capital One Cup','http://www1.skysports.com/watch/video/sports/football/competitions/capital-one-cup',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='formula-1':
                main.addDir('Formula 1 [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/12870/200/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Grand Prix','grand-prix',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Teams','f1Teams',180,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='rugby-union':
                main.addDir('Rugby Union [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/12610/200/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Aviva Premiership','http://www1.skysports.com/watch/video/sports/rugby-union/competitions/aviva-premiership',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Super Rugby','http://www1.skysports.com/watch/video/sports/rugby-union/competitions/super-rugby',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Heineken Cup','http://www1.skysports.com/watch/video/sports/rugby-union/competitions/heineken-cup',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
def SKYSPORTSTEAMS(murl):
        if murl=='premier-league':
                main.addDir('Premier League [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16426/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Arsenal','http://www1.skysports.com/watch/video/sports/football/teams/arsenal',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Aston Villa','http://www1.skysports.com/watch/video/sports/football/teams/aston-villa',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Chelsea','http://www1.skysports.com/watch/video/sports/football/teams/chelsea',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Everton','http://www1.skysports.com/watch/video/sports/football/teams/everton',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Fulham','http://www1.skysports.com/watch/video/sports/football/teams/fulham',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Liverpool','http://www1.skysports.com/watch/video/sports/football/teams/liverpool',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Manchester City','http://www1.skysports.com/watch/video/sports/football/teams/manchester-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Manchester United','http://www1.skysports.com/watch/video/sports/football/teams/manchester-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Newcastle United','http://www1.skysports.com/watch/video/sports/football/teams/newcastle-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Norwich City','http://www1.skysports.com/watch/video/sports/football/teams/norwich-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Queens Park Rangers','http://www1.skysports.com/watch/video/sports/football/teams/queens-park-rangers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Reading','http://www1.skysports.com/watch/video/sports/football/teams/reading',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Southampton','http://www1.skysports.com/watch/video/sports/football/teams/southampton',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Stoke City','http://www1.skysports.com/watch/video/sports/football/teams/stoke-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sunderland','http://www1.skysports.com/watch/video/sports/football/teams/sunderland',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Swansea City','http://www1.skysports.com/watch/video/sports/football/teams/swansea-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Tottenham Hotspur','http://www1.skysports.com/watch/video/sports/football/teams/tottenham-hotspur',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('West Bromwich Albion','http://www1.skysports.com/watch/video/sports/football/teams/west-bromwich-albion',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('West Ham United','http://www1.skysports.com/watch/video/sports/football/teams/west-ham-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Wigan Athletic','http://www1.skysports.com/watch/video/sports/football/teams/wigan-athletic',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                
        if murl=='championship':
                main.addDir('Championship [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16428/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Barnsley','http://www1.skysports.com/watch/video/sports/football/teams/barnsley',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Birmingham City','http://www1.skysports.com/watch/video/sports/football/teams/birmingham-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Blackburn Rovers','http://www1.skysports.com/watch/video/sports/football/teams/blackburn-rovers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Blackpool','http://www1.skysports.com/watch/video/sports/football/teams/blackpool',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bolton Wanderers','http://www1.skysports.com/watch/video/sports/football/teams/bolton-wanderers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Brighton','http://www1.skysports.com/watch/video/sports/football/teams/brighton',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bristol City','http://www1.skysports.com/watch/video/sports/football/teams/bristol-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Burnley','http://www1.skysports.com/watch/video/sports/football/teams/burnley',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Cardiff City','http://www1.skysports.com/watch/video/sports/football/teams/cardiff-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Charlton Athletic','http://www1.skysports.com/watch/video/sports/football/teams/charlton-athletic',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Crystal Palace','http://www1.skysports.com/watch/video/sports/football/teams/crystal-palace',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Derby County','http://www1.skysports.com/watch/video/sports/football/teams/derby-county',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Huddersfield Town','http://www1.skysports.com/watch/video/sports/football/teams/huddersfield-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Hull City','http://www1.skysports.com/watch/video/sports/football/teams/hull-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Ipswich Town','http://www1.skysports.com/watch/video/sports/football/teams/ipswich-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Leeds United','http://www1.skysports.com/watch/video/sports/football/teams/leeds-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Leicester City','http://www1.skysports.com/watch/video/sports/football/teams/leicester-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Middlesbrough','http://www1.skysports.com/watch/video/sports/football/teams/middlesbrough',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Millwall','http://www1.skysports.com/watch/video/sports/football/teams/millwall',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Nottingham Forest','http://www1.skysports.com/watch/video/sports/football/teams/nottingham-forest',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Peterborough United','http://www1.skysports.com/watch/video/sports/football/teams/peterborough-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sheffield Wednesday','http://www1.skysports.com/watch/video/sports/football/teams/sheffield-wednesday',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Watford','http://www1.skysports.com/watch/video/sports/football/teams/watford',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Wolverhampton','http://www1.skysports.com/watch/video/sports/football/teams/wolverhampton',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='league-one':
                main.addDir('League One [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16478/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bournemouth','http://www1.skysports.com/watch/video/sports/football/teams/bournemouth',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Brentford','http://www1.skysports.com/watch/video/sports/football/teams/brentford',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bury','http://www1.skysports.com/watch/video/sports/football/teams/bury',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Carlisle United','http://www1.skysports.com/watch/video/sports/football/teams/carlisle-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Colchester United','http://www1.skysports.com/watch/video/sports/football/teams/colchester-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Coventry City','http://www1.skysports.com/watch/video/sports/football/teams/coventry-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Crawley Town','http://www1.skysports.com/watch/video/sports/football/teams/crawley-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Crewe Alexandra','http://www1.skysports.com/watch/video/sports/football/teams/crewe-alexandra',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Doncaster','http://www1.skysports.com/watch/video/sports/football/teams/doncaster',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Hartlepool United','http://www1.skysports.com/watch/video/sports/football/teams/hartlepool-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Leyton Orient','http://www1.skysports.com/watch/video/sports/football/teams/leyton-orient',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Milton Keynes Dons','http://www1.skysports.com/watch/video/sports/football/teams/milton-keynes-dons',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Notts County','http://www1.skysports.com/watch/video/sports/football/teams/notts-county',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Oldham Athletic','http://www1.skysports.com/watch/video/sports/football/teams/oldham-athletic',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Portsmouth','http://www1.skysports.com/watch/video/sports/football/teams/portsmouth',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Preston North End','http://www1.skysports.com/watch/video/sports/football/teams/preston-north-end',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Scunthorpe United','http://www1.skysports.com/watch/video/sports/football/teams/scunthorpe-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sheffield United','http://www1.skysports.com/watch/video/sports/football/teams/sheffield-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Shrewsbury Town','http://www1.skysports.com/watch/video/sports/football/teams/shrewsbury-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Stevenage','http://www1.skysports.com/watch/video/sports/football/teams/stevenage',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Swindon Town','http://www1.skysports.com/watch/video/sports/football/teams/swindon-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Tranmere Rovers','http://www1.skysports.com/watch/video/sports/football/teams/tranmere-rovers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Walsall','http://www1.skysports.com/watch/video/sports/football/teams/walsall',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Yeovil Town','http://www1.skysports.com/watch/video/sports/football/teams/yeovil-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='league-two':
                main.addDir('League Two [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16478/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('AFC Wimbledon','http://www1.skysports.com/watch/video/sports/football/teams/afc-wimbledon',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Accrington Stanley','http://www1.skysports.com/watch/video/sports/football/teams/accrington-stanley',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Aldershot','http://www1.skysports.com/watch/video/sports/football/teams/aldershot',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Barnet FC','http://www1.skysports.com/watch/video/sports/football/teams/barnet-fc',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bradford City','http://www1.skysports.com/watch/video/sports/football/teams/bradford-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bristol Rovers','http://www1.skysports.com/watch/video/sports/football/teams/bristol-rovers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Burton Albion','http://www1.skysports.com/watch/video/sports/football/teams/burton-albion',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Cheltenham Town','http://www1.skysports.com/watch/video/sports/football/teams/cheltenham-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Chesterfield','http://www1.skysports.com/watch/video/sports/football/teams/chesterfield',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Dagenham and Redbridge','http://www1.skysports.com/watch/video/sports/football/teams/dagenham-and-redbridge',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Exeter City','http://www1.skysports.com/watch/video/sports/football/teams/exeter-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Fleetwood Town','http://www1.skysports.com/watch/video/sports/football/teams/fleetwood-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Gillingham','http://www1.skysports.com/watch/video/sports/football/teams/gillingham',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Hereford','http://www1.skysports.com/watch/video/sports/football/teams/hereford',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Macclesfield Town','http://www1.skysports.com/watch/video/sports/football/teams/macclesfield-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Morecambe','http://www1.skysports.com/watch/video/sports/football/teams/morecambe',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Northampton Town','http://www1.skysports.com/watch/video/sports/football/teams/northampton-town',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Oxford Utd','http://www1.skysports.com/watch/video/sports/football/teams/oxford-utd',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Plymouth Argyle','http://www1.skysports.com/watch/video/sports/football/teams/plymouth-argyle',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Port Vale','http://www1.skysports.com/watch/video/sports/football/teams/port-vale',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Rochdale','http://www1.skysports.com/watch/video/sports/football/teams/rochdale',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Rotherham United','http://www1.skysports.com/watch/video/sports/football/teams/rotherham-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Southend United','http://www1.skysports.com/watch/video/sports/football/teams/southend-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Torquay United','http://www1.skysports.com/watch/video/sports/football/teams/torquay-united',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Wycombe Wanderers','http://www1.skysports.com/watch/video/sports/football/teams/wycombe-wanderers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('York City','http://www1.skysports.com/watch/video/sports/football/teams/york-city',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='scottish-football':
                main.addDir('Scottish Football [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16480/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Aberdeen','http://www1.skysports.com/watch/video/sports/football/teams/aberdeen',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Celtic','http://www1.skysports.com/watch/video/sports/football/teams/celtic',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Rangers','http://www1.skysports.com/watch/video/sports/football/teams/rangers',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='primera-liga':
                main.addDir('Primera Liga [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/16995/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Athletic Bilbao','http://www1.skysports.com/watch/video/sports/football/teams/athletic-bilbao',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Atletico Madrid','http://www1.skysports.com/watch/video/sports/football/teams/atletico-madrid',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Barcelona','http://www1.skysports.com/watch/video/sports/football/teams/barcelona',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Celta Vigo','http://www1.skysports.com/watch/video/sports/football/teams/celta-vigo',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Deportivo La Coruna','http://www1.skysports.com/watch/video/sports/football/teams/deportivo-la-coruna',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Espanyol','http://www1.skysports.com/watch/video/sports/football/teams/espanyol',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Getafe','http://www1.skysports.com/watch/video/sports/football/teams/getafe',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Granada','http://www1.skysports.com/watch/video/sports/football/teams/granada',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Levante','http://www1.skysports.com/watch/video/sports/football/teams/levante',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Malaga','http://www1.skysports.com/watch/video/sports/football/teams/malaga',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Osasuna','http://www1.skysports.com/watch/video/sports/football/teams/osasuna',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Racing Santander','http://www1.skysports.com/watch/video/sports/football/teams/racing-santander',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Rayo Vallecano','http://www1.skysports.com/watch/video/sports/football/teams/rayo-vallecano',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Betis','http://www1.skysports.com/watch/video/sports/football/teams/real-betis',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Madrid','http://www1.skysports.com/watch/video/sports/football/teams/real-madrid',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Mallorca','http://www1.skysports.com/watch/video/sports/football/teams/real-mallorca',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Sociedad','http://www1.skysports.com/watch/video/sports/football/teams/real-sociedad',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Valladolid','http://www1.skysports.com/watch/video/sports/football/teams/real-valladolid',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Real Zaragoza','http://www1.skysports.com/watch/video/sports/football/teams/real-zaragoza',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sevilla','http://www1.skysports.com/watch/video/sports/football/teams/sevilla',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sporting Gijon','http://www1.skysports.com/watch/video/sports/football/teams/sporting-gijon',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Tenerife','http://www1.skysports.com/watch/video/sports/football/teams/tenerife',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('UD Almeria','http://www1.skysports.com/watch/video/sports/football/teams/ud-almeria',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Valencia','http://www1.skysports.com/watch/video/sports/football/teams/valencia',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Villarreal','http://www1.skysports.com/watch/video/sports/football/teams/villarreal',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Xerez','http://www1.skysports.com/watch/video/sports/football/teams/xerez',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='grand-prix':
                main.addDir('Grand Prix [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/27438/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Australia','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/australia',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Malaysia','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/malaysia',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('China','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/china',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Bahrain','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/bahrain',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Spain','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/spain',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Monaco','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/monaco',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Canada','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/canada',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Great Britain','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/great-britain',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Germany','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/germany',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Hungary','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/hungary',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Belgium','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/belgium',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Italy','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/italy',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Singapore','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/singapore',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Korea','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/korea',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Japan','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/japan',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('India','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/india',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Abu Dhabi','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/abu-dhabi',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('United States','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/united-states',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Brazil','http://www1.skysports.com/watch/video/sports/formula-1/grandprix/brazil',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
        if murl=='f1Teams':
                main.addDir('Teams [COLOR red]All Videos[/COLOR]','http://www1.skysports.com/watch/more/5/28292/100/1',173,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Caterham','http://www1.skysports.com/watch/video/sports/formula-1/teams/caterham',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Ferrari','http://www1.skysports.com/watch/video/sports/formula-1/teams/ferrari',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Force India','http://www1.skysports.com/watch/video/sports/formula-1/teams/force-india',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Lotus','http://www1.skysports.com/watch/video/sports/formula-1/teams/lotus',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Marussia','http://www1.skysports.com/watch/video/sports/formula-1/teams/marussia',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('McLaren','http://www1.skysports.com/watch/video/sports/formula-1/teams/mclaren',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Mercedes GP','http://www1.skysports.com/watch/video/sports/formula-1/teams/mercedes-gp',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Red Bull','http://www1.skysports.com/watch/video/sports/formula-1/teams/red-bull',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Sauber','http://www1.skysports.com/watch/video/sports/formula-1/teams/sauber',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Toro Rosso','http://www1.skysports.com/watch/video/sports/formula-1/teams/toro-rosso',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))
                main.addDir('Williams','http://www1.skysports.com/watch/video/sports/formula-1/teams/williams',176,"%s/art/skysports.png"%selfAddon.getAddonInfo("path"))


def SKYSPORTSTV(murl):
        main.GA("SkySportsTV","List")
        link=main.OPENURL(murl)
        link=link.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
        match = re.compile('<img src=".+?" data-src="(.+?)" class=".+?">                                                                                                                    </a>                                </div>                                <div class=".+?">                                    <a href="(.+?)" class=".+?">                                        <h4 class=".+?">(.+?)</h4>').findall(link)
        for thumb,url, name in match:
            thumb=thumb.replace('16-9/#{30}','384x216')
            url=url.replace('watch/tv-shows','watch/video/tv-shows').replace('/fantasyFC','/watch/video/tv-shows/fantasyFC')
            main.addDir(name,'http://www1.skysports.com'+url,176,thumb)
        main.VIEWSB()

def SKYSPORTSList(murl):
        main.GA("SkySports","List")
        link=main.OPENURL(murl)
        link=link.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
        match=re.compile('<a href="(.+?)" class=".+?">                                <img src=".+?" data-src="(.+?)" class=".+?">                                                                    <div class=".+?"><span class=".+?"></span></div>                                                            </a>                        </div>                        <div class=".+?">                            <a href=".+?" class="-a-block">                                <h4 class=".+?">(.+?)</h4>                                                                    <p class=".+?">(.+?)</p>                                                                            <button class=".+?">(.+?)</button>').findall(link)
        for url,thumb,name,date,typ in match:
                thumb=thumb.replace('16-9/#{30}','384x216')
                if name!='Sky Sports News Report':
                        if typ=='Watch Now':
                                main.addPlay(name+'   [COLOR red]'+date+'[/COLOR]',url,174,thumb)
                        else:
                                main.addPlay('[COLOR red]'+name+'[/COLOR]'+'   '+date,url,177,thumb)

def SKYSPORTSList2(murl):
        main.GA("SkySports","List")
        link=main.OPENURL(murl)
        link=link.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
        page=re.compile('data-current-page=".+?" data-pattern="(.+?)">').findall(link)
        if len(page)>0:
                for durl in page:
                        durl=durl.replace('{currentPage}','1').replace('/12/','/75/')
                link2=main.OPENURL('http://www1.skysports.com'+durl)
                link2=link2.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
                match=re.compile('<a href="(.+?)" class=".+?">                                <img src=".+?" data-src="(.+?)" class=".+?">                                                                    <div class=".+?"><span class=".+?"></span></div>                                                            </a>                        </div>                        <div class=".+?">                            <a href=".+?" class="-a-block">                                <h4 class=".+?">(.+?)</h4>                                                                    <p class=".+?">(.+?)</p>                                                                            <button class=".+?">(.+?)</button>').findall(link2)
                for url,thumb,name,date,typ in match:
                        thumb=thumb.replace('16-9/#{30}','384x216')
                        if name!='Sky Sports News Report':
                                if typ=='Watch Now':
                                        main.addPlay(name+'   [COLOR red]'+date+'[/COLOR]',url,174,thumb)
                                else:
                                        main.addPlay('[COLOR red]'+name+'[/COLOR]'+'   '+date,url,177,thumb)
        else:
                xbmc.executebuiltin("XBMC.Notification(Sorry!,No Video's to list,3000)")

        
        

def SKYSPORTSLink(mname,murl):
        main.GA("SkySports","Watched")
        xbmc.executebuiltin("XBMC.Notification(Please Wait!,Playing Video,1500)")
        playlist = xbmc.PlayList(xbmc.PLAYLIST_VIDEO)
        playlist.clear()
        ok= True
        link=main.OPENURL(murl)
        link=link.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
        match=re.compile('data-html5-video-url="(.+?)" >').findall(link)
        stream_url=match[0]
        desc=re.compile('<meta name="description" content="(.+?)"/>').findall(link)
        thumb=re.compile("<link rel='image_src' href='(.+?)' />").findall(link)
        listitem = xbmcgui.ListItem(mname, thumbnailImage= thumb[0])
        listitem.setInfo("Video", infoLabels={ "Title": mname, "Plot": desc[0]})
        playlist.add(stream_url,listitem)
        xbmcPlayer = xbmc.Player()
        xbmcPlayer.play(playlist)
        return ok
